add the calssification catagory of test case (farEdge Telco NonTelco)
test-network-function/test-network-function-claim pull request #82
Opened 2023-03-19 09:01 UTC by aabughosh

2023-03-19 13:01 UTC, shimritproj approved these changes

2023-03-20 14:38 UTC, sebrandon1 requested changes
Typos!

2023-03-20 14:38 UTC, sebrandon1 commented on pkg/claim/catalog.go
> +// struct for calssification
```suggestion
// struct for classification
```

2023-03-20 14:38 UTC, sebrandon1 commented on pkg/claim/catalog.go
> +type CatagoryClassification struct {
```suggestion
type CategoryClassification struct {
```

2023-03-20 14:38 UTC, sebrandon1 commented on pkg/claim/catalog.go
> +	Catagoryclassification CatagoryClassification `json:"Catagoryclassification" yaml:"Catagoryclassification"`
```suggestion
	// classification for each test case
	Categoryclassification CategoryClassification `json:"Categoryclassification" yaml:"Categoryclassification"`
```

2023-03-20 15:12 UTC, sebrandon1 approved these changes

2023-03-20 15:12 UTC, merged